// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WebApp.Models;

#nullable disable

namespace WebApp.Context
{
    public partial class GradeDbContext : DbContext
    {
        public GradeDbContext()
        {
        }

        public GradeDbContext(DbContextOptions<GradeDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<ClassCourse> ClassCourse { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Major> Major { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentCourse> StudentCourse { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<TeacherCourse> TeacherCourse { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<StudentFull> StudentFull { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Chinese_PRC_CI_AS");

            modelBuilder.Entity<Class>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.ToTable("Class18");

                entity.Property(e => e.Id)
                    .HasMaxLength(10)
                    .HasColumnName("Id18")
                    .IsFixedLength(true);

                entity.Property(e => e.MajorId)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("MajorId18")
                    .IsFixedLength(true);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("Name18")
                    .IsFixedLength(true);

                entity.HasOne(d => d.MajorNavigation)
                    .WithMany(p => p.Classes)
                    .HasForeignKey(d => d.MajorId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_Class18_Major18");
            });

            modelBuilder.Entity<ClassCourse>(entity =>
            {
                entity.HasKey(e => new {e.CourseId, e.ClassId});

                entity.ToTable("ClassCourse18");

                entity.HasIndex(e => new {StkqClassId18 = e.ClassId, StkqCourseId18 = e.CourseId }, "IX_ClassCourse18")
                    .IsUnique();

                entity.Property(e => e.ClassId)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("ClassId18")
                    .IsFixedLength(true);

                entity.Property(e => e.CourseId)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("CourseId18")
                    .IsFixedLength(true);

                entity.HasOne(d => d.ClassNavigation)
                    .WithMany()
                    .HasForeignKey(d => d.ClassId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ClassCourse18_Class18");

                entity.HasOne(d => d.CourseNavigation)
                    .WithMany()
                    .HasForeignKey(d => d.CourseId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ClassCourse18_Course18");
            });

            modelBuilder.Entity<Course>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.ToTable("Course18");

                entity.Property(e => e.Id)
                    .HasMaxLength(10)
                    .HasColumnName("Id18")
                    .IsFixedLength(true);

                entity.Property(e => e.Credit).HasColumnName("Credit18");

                entity.Property(e => e.ExamMethod)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("ExamMethod18")
                    .IsFixedLength(true);

                entity.Property(e => e.Hours).HasColumnName("Hours18");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("Name18")
                    .IsFixedLength(true);

                entity.Property(e => e.Semester)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("Semester18")
                    .IsFixedLength(true);
            });

            modelBuilder.Entity<Major>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.ToTable("Major18");

                entity.Property(e => e.Id)
                    .HasMaxLength(10)
                    .HasColumnName("Id18")
                    .IsFixedLength(true);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("Name18")
                    .IsFixedLength(true);
            });

            modelBuilder.Entity<Student>(entity =>
            {
                entity.HasKey(e => e.UserId)
                    .HasName("PK_Student18_1");

                entity.ToTable("Student18");

                entity.Property(e => e.UserId)
                    .HasMaxLength(10)
                    .HasColumnName("UserId18")
                    .IsFixedLength(true);

                entity.Property(e => e.ClassId)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("ClassId18")
                    .IsFixedLength(true);

                entity.Property(e => e.Credit)
                    .HasColumnName("Credit18")
                    .HasDefaultValueSql("((0))");

                entity.Property(e => e.SourcePlace)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("SourcePlace18")
                    .IsFixedLength(true);

                entity.HasOne(d => d.ClassNavigation)
                    .WithMany(p => p.Students)
                    .HasForeignKey(d => d.ClassId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Student18_Class18");

                entity.HasOne(d => d.UserNavigation)
                    .WithOne(p => p.Student)
                    .HasForeignKey<Student>(d => d.UserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Student18_User18");
            });

            modelBuilder.Entity<StudentCourse>(entity =>
            {
                entity.HasKey(e => new {e.CourseId, e.StudentId});

                entity.ToTable("StudentCourse18");

                entity.HasIndex(e => new {StkqStudentId18 = e.StudentId, StkqCourseId18 = e.CourseId }, "IX_StudentCourse18")
                    .IsUnique();

                entity.Property(e => e.CourseId)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("CourseId18")
                    .IsFixedLength(true);

                entity.Property(e => e.Score).HasColumnName("Score18");

                entity.Property(e => e.StudentId)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("StudentId18")
                    .IsFixedLength(true);

                entity.HasOne(d => d.CourseNavigation)
                    .WithMany()
                    .HasForeignKey(d => d.CourseId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_StudentCourse18_Course18");

                entity.HasOne(d => d.StudentNavigation)
                    .WithMany()
                    .HasForeignKey(d => d.StudentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_StudentCourse18_Student18");
            });

            modelBuilder.Entity<Teacher>(entity =>
            {
                entity.HasKey(e => e.UserId);

                entity.ToTable("Teacher18");

                entity.Property(e => e.UserId)
                    .HasMaxLength(10)
                    .HasColumnName("UserId18")
                    .IsFixedLength(true);

                entity.Property(e => e.Telephone)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("Telephone18")
                    .IsFixedLength(true);

                entity.Property(e => e.Title)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("Title18")
                    .IsFixedLength(true);

                entity.HasOne(d => d.UserNavigation)
                    .WithOne(p => p.Teacher)
                    .HasForeignKey<Teacher>(d => d.UserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Teacher18_User18");
            });

            modelBuilder.Entity<TeacherCourse>(entity =>
            {
                entity.HasKey(e => new {e.CourseId, e.TeacherId});

                entity.ToTable("TeacherCourse18");

                entity.HasIndex(e => new {StkqTeacherId18 = e.TeacherId, StkqCourseId18 = e.CourseId }, "IX_TeacherCourse18")
                    .IsUnique();

                entity.Property(e => e.CourseId)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("CourseId18")
                    .IsFixedLength(true);

                entity.Property(e => e.TeacherId)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("TeacherId18")
                    .IsFixedLength(true);

                entity.HasOne(d => d.CourseNavigation)
                    .WithMany()
                    .HasForeignKey(d => d.CourseId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TeacherCourse18_Course18");

                entity.HasOne(d => d.TeacherNavigation)
                    .WithMany()
                    .HasForeignKey(d => d.TeacherId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TeacherCourse18_Teacher18");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.ToTable("User18");

                entity.Property(e => e.Id)
                    .HasMaxLength(10)
                    .HasColumnName("Id18")
                    .IsFixedLength(true);

                entity.Property(e => e.Age).HasColumnName("Age18");

                entity.Property(e => e.Gender)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("Gender18")
                    .IsFixedLength(true);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("Name18")
                    .IsFixedLength(true);

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnName("Password18")
                    .IsFixedLength(true);

                entity.Property(e => e.Role)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("Role18")
                    .IsFixedLength(true);
            });

            modelBuilder.Entity<StudentFull>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("StudentFull");

                entity.Property(e => e.Class)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.Property(e => e.ClassId)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.Property(e => e.Gender)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.Property(e => e.Major)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.Property(e => e.MajorId)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.Property(e => e.SourcePlace)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.Property(e => e.StudentId)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength(true);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite(@"Data Source=D:\db.db;");
        }
    }
}